# general settings
name: Deblurring_Restormer
model_type: ImageCleanModel
scale: 1
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 100

# dataset and data loader settings
datasets:
  train:
    name: TrainSet
    type: Dataset_PairedImage
    dataroot_gt: ./Motion_Deblurring/Datasets/train/GoPro/target_crops
    dataroot_lq: ./Motion_Deblurring/Datasets/train/GoPro/input_crops
    geometric_augs: true

    filename_tmpl: '{}'
    io_backend:
      type: disk

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 4

    ### ------- Training on single fixed-patch size 128x128---------
    mini_batch_sizes: [4]
    iters: [300000]  # 300000
    gt_size: 256
    gt_sizes: [256]
    ### ------------------------------------------------------------

    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: ValSet
    type: Dataset_PairedImage
    dataroot_gt: ./Motion_Deblurring/Datasets/val/GoPro/target_crops
    dataroot_lq: ./Motion_Deblurring/Datasets/val/GoPro/input_crops
    io_backend:
      type: disk

#network structures


network_g:
  type: Uformer_OriKV_Qsigmoid

# path
path:
  pretrain_network_g: ~
  # pretrain_network_g: /root/Restormer-main/Motion_Deblurring/pretrained_models/motion_deblurring.pth
  # strict_load_g: false
  strict_load_g: true
  resume_state: ~

# training settings
train:
  total_iter: 600000
  warmup_iter: -1 # no warm up
  use_grad_clip: true

  # Split 300k iterations into two cycles.
  # 1st cycle: fixed 3e-4 LR for 92k iters.
  # 2nd cycle: cosine annealing (3e-4 to 1e-6) for 208k iters.
  scheduler:
    type: CosineAnnealingRestartCyclicLR
    periods: [184000, 416000]
    restart_weights: [1,1]
    eta_mins: [0.0003,0.000001]

  mixing_augs:
    mixup: false
    mixup_beta: 1.2
    use_identity: true

  optim_g:
    type: AdamW
    lr: !!float 3e-4
    #lr: !!float 1e-4
    weight_decay: !!float 1e-4
    #weight_decay: !!float 2e-4
    betas: [0.9, 0.999]
  
  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1
    reduction: mean

  fft_loss_opt:
    type: FFTLoss
    loss_weight: 0.1
    reduction: mean


# validation settings
val:
  window_size: 8
  val_freq: !!float 4e3
  save_img: false
  rgb2bgr: true
  use_image: true
  max_minibatch: 8

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 1000
  save_checkpoint_freq: !!float 8e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
